server:
  port: 8080

spring:
  application:
    name: eureka-server0

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8080/eureka




#spring:
#  cloud:
#    config:
#      uri: http://localhost:8081

# spring.cloud.config.username=root
# spring.cloud.config.password=s3cr3t
# spring.cloud.config.name=conf
# spring.cloud.config.uri=http://localhost:8081
