server:
  port: 8082

spring:
  application:
    name: eureka-client2

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8080/eureka}
    fetchRegistry: true

management:
  endpoint:
    health:
      show-details: always

